import type { Strings } from './types';

export const EN: Strings = {
  actions: {
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    back: 'Back',
    add: 'Add',
    create: 'Create',
    close: 'Close',
    loading: 'Loading...',
    saving: 'Saving...',
    confirm: 'Confirm',
    copy: 'Copy',
    copied: 'Copied!',
    export: 'Export',
    refresh: 'Refresh',
    connect: 'Connect',
    manage: 'Manage',
    invite: 'Invite',
    next: 'Next',
    previous: 'Previous',
    finish: 'Finish',
  },
  auth: {
    login: {
      title: 'Sign in to your account',
      subtitle: 'Welcome back to SYRAX',
      emailLabel: 'Email',
      emailPlaceholder: 'your@email.com',
      passwordLabel: 'Password',
      passwordPlaceholder: '••••••••',
      submit: 'Sign in',
    },
  },
  nav: {
    sectionPrincipal: 'Main',
    sectionSistema: 'System',
    dashboard: 'Dashboard',
    leads: 'Leads',
    oportunidades: 'Opportunities',
    conversas: 'Conversations',
    recuperacoes: 'Recoveries',
    integracoes: 'Integrations',
    relatorios: 'Reports',
    configuracoes: 'Settings',
    logout: 'Sign out',
  },
  dashboard: {
    title: 'Dashboard',
    flowCard: {
      title: 'How SYRAX works',
      step1: 'Inactive Leads Detected',
      step2: 'AI Analyzes and Acts',
      step3: 'Automatic Conversion',
    },
    kpi: {
      receitaRecuperada: 'Recovered Revenue',
      leadsReativados: 'Reactivated Leads',
      conversoesGeradas: 'Conversions Generated',
      emNegociacao: 'In Negotiation',
      leadsNovos: 'New Leads',
      leadsPerdidos: 'Lost Leads',
    },
    charts: {
      receitaTitle: 'Recovered Revenue — 14 days',
      funilTitle: 'Conversion Funnel',
      funilStages: ['Leads', 'Contact', 'Proposal', 'Closed'],
    },
    acoesIa: {
      title: 'Latest AI Actions',
      colLead: 'Lead',
      colAcao: 'Action',
      colCanal: 'Channel',
      colResultado: 'Result',
      colHorario: 'Time',
    },
  },
  lead: {
    title: 'Leads',
    searchPlaceholder: 'Search by name, email or phone...',
    filterAll: 'All',
    filterNovo: 'New',
    filterEmContato: 'In Contact',
    filterConvertido: 'Converted',
    filterPerdido: 'Lost',
    colNome: 'Name',
    colEmpresa: 'Company',
    colStatus: 'Status',
    colOrigem: 'Origin',
    colUltimoContato: 'Last Contact',
    colValor: 'Value',
    colScore: 'Score',
    colAcao: 'Action',
    status: {
      novo: 'New',
      em_contato: 'In Contact',
      convertido: 'Converted',
      perdido: 'Lost',
    },
    abandonType: {
      pix: 'Pix',
      boleto: 'Boleto',
      cart: 'Cart',
    },
    whatsappTemplate: (name: string, product: string, value: string) =>
      `Hi ${name}! I noticed you were interested in ${product} ($${value}). Can I help you complete your purchase? 😊`,
    triggerAi: 'Trigger AI',
    initiateContact: 'Initiate Contact',
    noLeads: 'No leads found.',
    temperature: {
      quente: 'Hot',
      morno: 'Warm',
      frio: 'Cold',
    },
    detail: {
      title: 'Lead Details',
      timeline: 'History',
      addNote: 'Add note',
      notePlaceholder: 'Write an observation...',
    },
  },
  oportunidades: {
    title: 'Opportunities',
    kpi: {
      totalRisco: 'Total at Risk',
      altaProbabilidade: 'High Probability',
      tempoMedioParado: 'Average Idle Time',
    },
    diasSemContato: (days: number) => `${days} ${days === 1 ? 'day' : 'days'} without contact`,
    horasSemContato: (hours: number) => `${Math.round(hours)}h without contact`,
    emptyState: 'No opportunities at the moment.',
  },
  conversas: {
    title: 'Conversations',
    search: 'Search conversation...',
    pauseAi: 'Pause AI',
    noConversas: 'No conversations yet.',
    typeMessage: 'Type a message...',
  },
  recuperacoes: {
    title: 'Recoveries',
    kpi: {
      totalRecuperado: 'Total Recovered',
      conversoes: 'Conversions',
      ticketMedio: 'Average Ticket',
      roiMedio: 'Average ROI',
    },
    colLead: 'Lead',
    colValor: 'Value',
    colData: 'Date',
    colCanal: 'Channel',
    colDuracao: 'Duration',
    colStatus: 'Status',
    fechadoViaIa: 'Closed via AI',
    duracao: (days: number) => `${days} ${days === 1 ? 'day' : 'days'}`,
    noRecuperacoes: 'No recoveries yet.',
  },
  integracoes: {
    title: 'Integrations',
    webhookUrl: 'Webhook URL',
    totalEvents: (n: number) => `${n} events received`,
    status: {
      connected: 'Connected',
      disconnected: 'Disconnected',
    },
    platforms: {
      kiwify: 'Kiwify',
      hotmart: 'Hotmart',
      whatsapp: 'WhatsApp',
    },
    webhookInstructions: 'Copy the URL below and configure it in the platform dashboard.',
    whatsappMvpNote: 'WhatsApp via wa.me (MVP). Full API coming soon.',
  },
  relatorios: {
    title: 'Reports',
    dateFilter: {
      last7d: 'Last 7 days',
      last30d: 'Last 30 days',
      last90d: 'Last 90 days',
      custom: 'Custom',
    },
    charts: {
      leadsVsConversoes: 'Leads vs Conversions',
    },
    performance: {
      title: 'Campaign Performance',
      colCampanha: 'Campaign',
      colLeads: 'Leads',
      colContatos: 'Contacts',
      colConversoes: 'Conversions',
      colReceita: 'Revenue',
      colRoi: 'ROI',
    },
  },
  configuracoes: {
    title: 'Settings',
    tabs: {
      empresa: 'Company',
      equipe: 'Team',
      faturamento: 'Billing',
    },
    empresa: {
      title: 'Company Details',
      nameLabel: 'Name',
      cnpjLabel: 'CNPJ',
      sectorLabel: 'Sector',
    },
    equipe: {
      title: 'Team Members',
      inviteButton: 'Invite Operator',
      inviteEmailLabel: 'Operator email',
      inviteEmailPlaceholder: 'operator@company.com',
      roleAdmin: 'Admin',
      roleOperator: 'Operator',
    },
    faturamento: {
      title: 'Billing',
      comingSoon: 'Coming soon.',
    },
  },
  errors: {
    generic: 'Something went wrong. Please try again.',
    notFound: 'Page not found.',
    unauthorized: 'Unauthorized.',
    networkError: 'Connection error. Check your internet.',
  },
  search: {
    placeholder: 'Search...',
    noResults: 'No results found.',
  },
};
