export const PT_BR = {
  actions: {
    save: 'Salvar',
    cancel: 'Cancelar',
    delete: 'Excluir',
    edit: 'Editar',
    back: 'Voltar',
    add: 'Adicionar',
    create: 'Criar',
    close: 'Fechar',
    loading: 'Carregando...',
    saving: 'Salvando...',
    confirm: 'Confirmar',
    copy: 'Copiar',
    copied: 'Copiado!',
    export: 'Exportar',
    refresh: 'Atualizar',
    connect: 'Conectar',
    manage: 'Gerenciar',
    invite: 'Convidar',
    next: 'Próximo',
    previous: 'Anterior',
    finish: 'Finalizar',
  },
  auth: {
    login: {
      title: 'Entrar na sua conta',
      subtitle: 'Bem-vindo de volta ao SYRAX',
      emailLabel: 'E-mail',
      emailPlaceholder: 'seu@email.com',
      passwordLabel: 'Senha',
      passwordPlaceholder: '••••••••',
      submit: 'Entrar',
    },
  },
  nav: {
    sectionPrincipal: 'Principal',
    sectionSistema: 'Sistema',
    dashboard: 'Dashboard',
    leads: 'Leads',
    oportunidades: 'Oportunidades',
    conversas: 'Conversas',
    recuperacoes: 'Recuperações',
    integracoes: 'Integrações',
    relatorios: 'Relatórios',
    configuracoes: 'Configurações',
    logout: 'Sair',
  },
  dashboard: {
    title: 'Dashboard',
    flowCard: {
      title: 'Como o SYRAX funciona',
      step1: 'Leads Inativos Detectados',
      step2: 'IA Analisa e Age',
      step3: 'Conversão Automática',
    },
    kpi: {
      receitaRecuperada: 'Receita Recuperada',
      leadsReativados: 'Leads Reativados',
      conversoesGeradas: 'Conversões Geradas',
      emNegociacao: 'Em Negociação',
      leadsNovos: 'Leads Novos',
      leadsPerdidos: 'Leads Perdidos',
    },
    charts: {
      receitaTitle: 'Receita Recuperada — 14 dias',
      funilTitle: 'Funil de Conversão',
      funilStages: ['Leads', 'Contato', 'Proposta', 'Fechado'],
    },
    acoesIa: {
      title: 'Últimas Ações da IA',
      colLead: 'Lead',
      colAcao: 'Ação',
      colCanal: 'Canal',
      colResultado: 'Resultado',
      colHorario: 'Horário',
    },
  },
  lead: {
    title: 'Leads',
    searchPlaceholder: 'Buscar por nome, e-mail ou telefone...',
    filterAll: 'Todos',
    filterNovo: 'Novo',
    filterEmContato: 'Em Contato',
    filterConvertido: 'Convertido',
    filterPerdido: 'Perdido',
    colNome: 'Nome',
    colEmpresa: 'Empresa',
    colStatus: 'Status',
    colOrigem: 'Origem',
    colUltimoContato: 'Último Contato',
    colValor: 'Valor',
    colScore: 'Score',
    colAcao: 'Ação',
    status: {
      novo: 'Novo',
      em_contato: 'Em Contato',
      convertido: 'Convertido',
      perdido: 'Perdido',
    },
    abandonType: {
      pix: 'Pix',
      boleto: 'Boleto',
      cart: 'Carrinho',
    },
    whatsappTemplate: (name: string, product: string, value: string) =>
      `Olá ${name}! Vi que você se interessou pelo ${product} (R$ ${value}). Posso te ajudar a concluir sua compra? 😊`,
    triggerAi: 'Acionar IA',
    initiateContact: 'Iniciar Contato',
    noLeads: 'Nenhum lead encontrado.',
    temperature: {
      quente: 'Quente',
      morno: 'Morno',
      frio: 'Frio',
    },
    detail: {
      title: 'Detalhes do Lead',
      timeline: 'Histórico',
      addNote: 'Adicionar nota',
      notePlaceholder: 'Escreva uma observação...',
    },
  },
  oportunidades: {
    title: 'Oportunidades',
    kpi: {
      totalRisco: 'Total em Risco',
      altaProbabilidade: 'Alta Probabilidade',
      tempoMedioParado: 'Tempo Médio Parado',
    },
    diasSemContato: (days: number) => `${days} ${days === 1 ? 'dia' : 'dias'} sem contato`,
    horasSemContato: (hours: number) => `${Math.round(hours)}h sem contato`,
    emptyState: 'Nenhuma oportunidade no momento.',
  },
  conversas: {
    title: 'Conversas',
    search: 'Buscar conversa...',
    pauseAi: 'Pausar IA',
    noConversas: 'Nenhuma conversa ainda.',
    typeMessage: 'Digite uma mensagem...',
  },
  recuperacoes: {
    title: 'Recuperações',
    kpi: {
      totalRecuperado: 'Total Recuperado',
      conversoes: 'Conversões',
      ticketMedio: 'Ticket Médio',
      roiMedio: 'ROI Médio',
    },
    colLead: 'Lead',
    colValor: 'Valor',
    colData: 'Data',
    colCanal: 'Canal',
    colDuracao: 'Duração',
    colStatus: 'Status',
    fechadoViaIa: 'Fechado via IA',
    duracao: (days: number) => `${days} ${days === 1 ? 'dia' : 'dias'}`,
    noRecuperacoes: 'Nenhuma recuperação ainda.',
  },
  integracoes: {
    title: 'Integrações',
    webhookUrl: 'URL do Webhook',
    totalEvents: (n: number) => `${n} eventos recebidos`,
    status: {
      connected: 'Conectado',
      disconnected: 'Desconectado',
    },
    platforms: {
      kiwify: 'Kiwify',
      hotmart: 'Hotmart',
      whatsapp: 'WhatsApp',
    },
    webhookInstructions: 'Copie a URL abaixo e configure no painel da plataforma.',
    whatsappMvpNote: 'WhatsApp via wa.me (MVP). API completa em breve.',
  },
  relatorios: {
    title: 'Relatórios',
    dateFilter: {
      last7d: 'Últimos 7 dias',
      last30d: 'Últimos 30 dias',
      last90d: 'Últimos 90 dias',
      custom: 'Personalizado',
    },
    charts: {
      leadsVsConversoes: 'Leads vs Conversões',
    },
    performance: {
      title: 'Performance por Campanha',
      colCampanha: 'Campanha',
      colLeads: 'Leads',
      colContatos: 'Contatos',
      colConversoes: 'Conversões',
      colReceita: 'Receita',
      colRoi: 'ROI',
    },
  },
  configuracoes: {
    title: 'Configurações',
    tabs: {
      empresa: 'Empresa',
      equipe: 'Equipe',
      faturamento: 'Faturamento',
    },
    empresa: {
      title: 'Dados da Empresa',
      nameLabel: 'Nome',
      cnpjLabel: 'CNPJ',
      sectorLabel: 'Setor',
    },
    equipe: {
      title: 'Membros da Equipe',
      inviteButton: 'Convidar Operador',
      inviteEmailLabel: 'E-mail do operador',
      inviteEmailPlaceholder: 'operador@empresa.com',
      roleAdmin: 'Admin',
      roleOperator: 'Operador',
    },
    faturamento: {
      title: 'Faturamento',
      comingSoon: 'Em breve.',
    },
  },
  errors: {
    generic: 'Algo deu errado. Tente novamente.',
    notFound: 'Página não encontrada.',
    unauthorized: 'Acesso não autorizado.',
    networkError: 'Erro de conexão. Verifique sua internet.',
  },
  search: {
    placeholder: 'Buscar...',
    noResults: 'Nenhum resultado encontrado.',
  },
} as const;
