# Generated by Django 5.1 on 2026-05-10 23:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('whatsapp_sent', 'WhatsApp Sent'), ('status_change', 'Status Change'), ('note', 'Note'), ('ai_triggered', 'AI Triggered')], max_length=30)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('product_name', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('abandon_type', models.CharField(choices=[('pix', 'Pix'), ('boleto', 'Boleto'), ('cart', 'Cart')], default='cart', max_length=10)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_contato', 'Em Contato'), ('convertido', 'Convertido'), ('perdido', 'Perdido')], default='novo', max_length=20)),
                ('origin', models.CharField(default='manual', max_length=100)),
                ('score', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
