# Generated by Django 5.1 on 2026-05-10 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='companies.company'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='leads.lead'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', '-created_at'], name='leads_lead_company_6ce738_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'status'], name='leads_lead_company_2d29e3_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'score'], name='leads_lead_company_332e1d_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['lead', '-created_at'], name='leads_inter_lead_id_37e0f9_idx'),
        ),
    ]
