# Generated by Django 5.1 on 2026-05-10 23:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('kiwify', 'Kiwify'), ('hotmart', 'Hotmart'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected')], default='disconnected', max_length=20)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('total_events_received', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='companies.company')),
            ],
            options={
                'ordering': ['platform'],
                'indexes': [models.Index(fields=['company', 'platform'], name='integration_company_9de1e4_idx')],
                'unique_together': {('company', 'platform')},
            },
        ),
    ]
